# Generated by Django 6.0.5 on 2026-06-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
