# Generated by Django 6.0.5 on 2026-06-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_sourcing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclesourcingrequest',
            name='contacted',
        ),
        migrations.AddField(
            model_name='vehiclesourcingrequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('fulfilled', 'Fulfilled')], default='new', max_length=20),
        ),
    ]
