# Generated by Django 6.0.5 on 2026-06-30 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('vehicle', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=255)),
                ('postcode', models.CharField(max_length=12)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('fulfilled', 'Fulfilled')], default='new', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
