# Generated by Django 6.0.5 on 2026-06-18 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. "BMW 3 Series"', max_length=255)),
                ('subtitle', models.CharField(help_text='Trim/spec line, e.g. "2.0 320d M Sport Saloon Auto Euro 6 4dr"', max_length=255)),
                ('make', models.CharField(help_text='Brand, e.g. "BMW"', max_length=100)),
                ('model', models.CharField(help_text='Model, e.g. "3 Series"', max_length=100)),
                ('body_type', models.CharField(choices=[('SUV', 'SUV'), ('Hatchback', 'Hatchback'), ('Saloon', 'Saloon'), ('Estate', 'Estate'), ('Coupe', 'Coupe'), ('Convertible', 'Convertible'), ('MPV', 'MPV'), ('Van', 'Van')], max_length=20)),
                ('fuel', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Hybrid', 'Hybrid'), ('Electric', 'Electric'), ('Mild Hybrid', 'Mild Hybrid')], max_length=20)),
                ('transmission', models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual'), ('CVT', 'CVT'), ('Semi-Automatic', 'Semi-Automatic')], max_length=20)),
                ('colour', models.CharField(choices=[('Black', 'Black'), ('White', 'White'), ('Silver', 'Silver'), ('Grey', 'Grey'), ('Blue', 'Blue'), ('Red', 'Red'), ('Green', 'Green'), ('Orange', 'Orange')], max_length=20)),
                ('year', models.PositiveIntegerField(help_text='Registration year, e.g. 2019')),
                ('engine_cc', models.PositiveIntegerField(help_text='Engine size in CC, e.g. 1995')),
                ('engine', models.CharField(blank=True, help_text='Display engine, e.g. "2.0L"', max_length=20)),
                ('doors', models.PositiveSmallIntegerField(default=5)),
                ('seats', models.PositiveSmallIntegerField(default=5)),
                ('mileage', models.PositiveIntegerField(help_text='Mileage as a number, e.g. 42300')),
                ('price', models.PositiveIntegerField(help_text='Total price in £ (whole pounds), e.g. 14495')),
                ('monthly', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly payment in £, e.g. 245.00', max_digits=8, null=True)),
                ('mot_date', models.DateField(blank=True, help_text='MOT expiry date', null=True)),
                ('history_check', models.CharField(blank=True, default='All passed', max_length=120)),
                ('image', models.ImageField(help_text='Main/card thumbnail. Gallery images are added below.', upload_to='cars/')),
                ('description', models.TextField(blank=True, help_text='Marketing description shown on the detail page')),
                ('summary', models.TextField(blank=True, help_text='Vehicle Summary accordion')),
                ('performance', models.TextField(blank=True, help_text='Performance & Economy accordion')),
                ('interior', models.TextField(blank=True, help_text='Interior/Exterior accordion')),
                ('safety', models.TextField(blank=True, help_text='Safety/Other accordion')),
                ('video_url', models.URLField(blank=True, help_text='Video walkthrough URL (YouTube etc.)')),
                ('location_name', models.CharField(blank=True, max_length=255)),
                ('location_address', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold')], default='available', help_text="Only 'available' cars appear in stock listings", max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=120)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='cars.car')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='cars.car')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
