# Generated by Django 6.0.5 on 2026-06-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default='200.00', help_text='Refundable reservation deposit charged at checkout, in £.', max_digits=8),
        ),
    ]
