# Generated by Django 6.0.5 on 2026-06-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_deposit_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='carfeature',
            name='category',
            field=models.CharField(choices=[('Exterior', 'Exterior'), ('Interior', 'Interior'), ('Performance', 'Performance'), ('Audio and Communications', 'Audio and Communications')], default='Interior', max_length=40),
        ),
        migrations.AlterField(
            model_name='carfeature',
            name='text',
            field=models.CharField(max_length=200),
        ),
    ]
