# Generated by Django 6.0.5 on 2026-06-22 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_carfeature_category_alter_carfeature_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='interior',
        ),
        migrations.RemoveField(
            model_name='car',
            name='performance',
        ),
        migrations.RemoveField(
            model_name='car',
            name='safety',
        ),
        migrations.RemoveField(
            model_name='car',
            name='summary',
        ),
    ]
