# Generated by Django 6.0.5 on 2026-06-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_remove_car_interior_remove_car_performance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carfeature',
            name='category',
            field=models.CharField(choices=[('Exterior', 'Exterior'), ('Interior', 'Interior'), ('Performance', 'Performance'), ('Size and dimensions', 'Size and dimensions'), ('Audio and Communications', 'Audio and Communications')], default='Interior', max_length=40),
        ),
    ]
