# Generated by Django 6.0.5 on 2026-07-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_carfeature_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='reg',
            field=models.CharField(blank=True, default='', help_text='Registration number, e.g. "AB15 CDE"', max_length=20),
        ),
    ]
