# Generated by Django 6.0.5 on 2026-09-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_car_reg'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['make'], name='car_make_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['model'], name='car_model_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['body_type'], name='car_body_type_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['fuel'], name='car_fuel_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['transmission'], name='car_transmission_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['colour'], name='car_colour_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['status'], name='car_status_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['price'], name='car_price_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['mileage'], name='car_mileage_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['year'], name='car_year_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['created_at'], name='car_created_at_idx'),
        ),
    ]
