# Generated by Django 6.0.5 on 2026-06-18 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
        ('payments', '0002_payment_stripe_session_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='car',
            field=models.ForeignKey(blank=True, help_text='The vehicle this payment reserves (if any).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='cars.car'),
        ),
    ]
