# Generated by Django 6.0.5 on 2026-06-19 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0003_car_deposit_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('test_drive', 'Test Drive'), ('appointment', 'Appointment')], max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='cars.car')),
            ],
            options={
                'ordering': ['date', 'time'],
                'constraints': [models.UniqueConstraint(fields=('date', 'time'), name='unique_appointment_slot')],
            },
        ),
    ]
